server.port=8080

spring.application.name=ewm-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

stats.server.url=${STATS_SERVER_URL:http://localhost:9090}

management.endpoints.web.exposure.include=health,info
