CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(254) NOT NULL,
	name VARCHAR(250) NOT NULL,
	CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation VARCHAR(2000) NOT NULL,
	category_id BIGINT NOT NULL REFERENCES categories (id),
	created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	description VARCHAR(7000) NOT NULL,
	event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	initiator_id BIGINT NOT NULL REFERENCES users (id),
	lat DOUBLE PRECISION NOT NULL,
	lon DOUBLE PRECISION NOT NULL,
	paid BOOLEAN NOT NULL,
	participant_limit INTEGER NOT NULL,
	published_on TIMESTAMP WITHOUT TIME ZONE,
	request_moderation BOOLEAN NOT NULL,
	state VARCHAR(20) NOT NULL,
	title VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	event_id BIGINT NOT NULL REFERENCES events (id),
	requester_id BIGINT NOT NULL REFERENCES users (id),
	status VARCHAR(20) NOT NULL,
	CONSTRAINT uq_requests_event_requester UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pinned BOOLEAN NOT NULL,
	title VARCHAR(50) NOT NULL,
	CONSTRAINT uq_compilations_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilation_events (
	compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
	event_id BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
	CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_events_category ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator ON events (initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events (state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_requests_event ON requests (event_id);
CREATE INDEX IF NOT EXISTS idx_requests_requester ON requests (requester_id);
