server.port=9090

spring.application.name=stats-server

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stats}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stats}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

management.endpoints.web.exposure.include=health,info
